// Auto-generated by scripts/sync-cms-to-static.ts — DO NOT EDIT MANUALLY.
// Przed pierwszym sync: fallbacki dla dev / build bez credentials.

import { PAGE_HERO_IMAGES } from "./hero-images";

export type StaticCmsHeroEntry = {
	productImageUrl: string;
	productImageAlt: string;
	productImageWidth: number;
	productImageHeight: number;
};

export const STATIC_CMS_HERO: Partial<Record<"home" | "prezent", StaticCmsHeroEntry>> = {
	prezent: {
		productImageUrl: PAGE_HERO_IMAGES.prezent.src,
		productImageAlt: PAGE_HERO_IMAGES.prezent.alt,
		productImageWidth: 1200,
		productImageHeight: 1500,
	},
};
