import { categoryLabel, HUE_TRIADS } from "@/lib/products/constants";
import { DEFAULT_EPOCH_OPTIONS, epochLabelFor } from "@/lib/products/epoch-types";
import type { Product } from "@/lib/products/types";

const epochLabel = (value: string) => epochLabelFor(value, DEFAULT_EPOCH_OPTIONS);

const mockDefaults = { defects: [] as const, pickupOnly: false } satisfies Pick<
	Product,
	"defects" | "pickupOnly"
>;

/** Katalog lokalny — UI dev bez Medusa. Nie używać w produkcji. */
export const DEV_MOCK_PRODUCTS: Product[] = [
	{
		medusaId: "mock_wazon-rosenthal",
		slug: "wazon-rosenthal-art-deco-1934",
		name: "Wazon Rosenthal Art Deco 1934",
		price: 420,
		currencyCode: "pln",
		category: "porcelana",
		categoryLabel: categoryLabel("porcelana"),
		epoch: "art-deco",
		epochLabel: epochLabel("art-deco"),
		manufacturer: "Rosenthal",
		dimensions: "h 24 cm",
		condition: "Stan kolekcjonerski, bez uszkodzeń.",
		badges: ["unikat"],
		...mockDefaults,
		addedAt: "2026-03-01",
		story: "Wiedeńska porcelana z okresu międzywojnia — charakterystyczna forma i szkliwo.",
		shortDescription: "Wazon Art Deco z manufaktury Rosenthal, 1934.",
		imageHues: HUE_TRIADS.porcelana,
		images: [],
		popularity: 90,
		giftBestseller: true,
	},
	{
		medusaId: "mock-filianka-augarten",
		slug: "filianka-augarten-wieden",
		name: "Filianka Augarten Wien",
		price: 180,
		currencyCode: "pln",
		category: "porcelana",
		categoryLabel: categoryLabel("porcelana"),
		epoch: "lata-50",
		epochLabel: epochLabel("lata-50"),
		manufacturer: "Augarten",
		dimensions: "ø 8 cm",
		condition: "Delikatne ślady użytkowania na spodzie.",
		badges: ["bestseller"],
		...mockDefaults,
		addedAt: "2026-02-14",
		story: "Klasyczna filianka z wiedeńskiej manufaktury — punkt wejścia do świata porcelany.",
		shortDescription: "Filianka Augarten — poranna kawa jak w kawiarni.",
		imageHues: HUE_TRIADS.porcelana,
		images: [],
		popularity: 85,
	},
	{
		medusaId: "mock-wazon-szklo",
		slug: "wazon-szklo-bohemia",
		name: "Wazon szkło Bohemia",
		price: 260,
		currencyCode: "pln",
		category: "szklo",
		categoryLabel: categoryLabel("szklo"),
		epoch: "lata-60-70",
		epochLabel: epochLabel("lata-60-70"),
		manufacturer: "Bohemia",
		dimensions: "h 30 cm",
		condition: "Bez pęknięć, lekki mat na podstawie.",
		badges: ["fresh"],
		...mockDefaults,
		addedAt: "2026-04-10",
		story: "Czeskie szkło barwione — mocny akcent na komodzie lub parapecie.",
		shortDescription: "Wazon ze szkła Bohemia, lata 60.–70.",
		imageHues: HUE_TRIADS.szklo,
		images: [],
		popularity: 70,
	},
	{
		medusaId: "mock-lampa-dekor",
		slug: "lampa-dekor-secesja",
		name: "Lampa dekoracyjna secesja",
		price: 540,
		currencyCode: "pln",
		category: "dekoracje",
		categoryLabel: categoryLabel("dekoracje"),
		epoch: "secesja",
		epochLabel: epochLabel("secesja"),
		manufacturer: "—",
		dimensions: "h 42 cm",
		condition: "Sprawna instalacja, klosz oryginalny.",
		badges: ["unikat"],
		...mockDefaults,
		addedAt: "2026-01-20",
		story: "Secesyjna forma i ciepłe światło — wieczorny rytuał w salonie.",
		shortDescription: "Lampa dekoracyjna w stylu secesji.",
		imageHues: HUE_TRIADS.dekoracje,
		images: [],
		popularity: 60,
	},
];
